services:
  postgres:
    image: 'postgres:latest'
    restart: unless-stopped
    container_name: assa_abloy_lock_simulator_postgres_db
    environment:
      POSTGRES_DB: assa_abloy_lock_simulator
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    ports:
      - '5432:5432'

volumes:
  pgdata: