spring:
  application:
    name: interview

  jpa:
    hibernate:
      ddl-auto: update

  datasource:
    username: ${POSTGRES_USER}
    password: ${POSTGRES_password}
    url: jdbc://postgresql:localhost:5432/assa_abloy_lock_simulator
    driver-class-name: org.postgresql.Driver